#!/bin/bash
set -eo pipefail

cd "$(dirname "$0")"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication blockMesh
runApplication setFields
runApplication decomposePar -force
runParallel "$(getApplication)"

#------------------------------------------------------------------------------
